var globalResources = {
  withexecutedamount: "سفارشات داراي حجم انجام شده",
  weightvalue: "قیمت (وزنی-ارزشی)",
  validrequstisnotfound: "درخواست تسویه معتبری پیدا نشد",
  usernamesuccessfullychanged:
    "ویرایش نام کاربری با موفقیت انجام شد. لطفا دوباره وارد شوید",
  usernamelenghtpolicy: "حداقل تعداد کاراکتر رعایت نشده است",
  usernameisnoiseword: "نام کاربری انتخابی مجاز نیست",
  usernameischosenbefor: "نام کاربری قبلا انتخاب شده است.",
  usernamecannotbenationalcode:
    "نام کاربری نمی تواند کدملی باشد. لطفا نام کاربری دیگری انتخاب نمایید",
  user_adminplus: "کاربران با دسترسي خاص",
  updateorders: "بروزرسانی سفارشات",
  ttsfinancialdataprovider: "حساب نزدکارگزار (هماهنگ)",
  tsdonya: "کارگزاری توسعه دنیا",
  transactionnotfound: "تراکنش یافت نشد",
  transaction_reversed: "مبلغ به حساب مشتری بازگردانده شده است",
  transaction_not_found: "تراکنش یافت نشد",
  "transaction number": "شماره تراکنش",
  trading_session: "جلسه معاملات",
  totalquantity: "حجم سفارش",
  totalindex: "شاخص کل",
  tosefarda: "کارگزاری توسعه فردا",
  top50active: "50 شرکت فعال",
  top30big: "30 شرکت بزرگ",
  third_board: "(3)جبرانی",
  the_maximum_start_and_end_dates_must_be_5_days:
    "فاصله بین تاریخ ابتدا و انتها باید 5 روز باشد",
  textresourcekey_loginspecialtext: "اطلاعیه مهم",
  textresourcekey_loginsecuritytips: "نکات امنیتی (لاگین)",
  textresourcekey_loginmanagelinks: "مدیریت لینک (لاگین)",
  textresourcekey_loginlinks: "لینک های صفحه لاگین",
  tejaratnewfinancialdataprovider: "درگاه ایران کیش",
  tejaratfinancialdataprovider_irankish: "درگاه پرداخت ایران کیش ",
  tejaratfinancialdataprovider: "حساب بانک تجارت",
  tbs_cashflowstate_troubleshooting: "در حال رفع مشکل",
  tbs_cashflowstate_reviewmode: "در حال بررسی",
  tbs_cashflowstate_done: "اقدام گردید",
  tbs_cashflowstate_deleted: "حذف گردید",
  tbs_cashflowstate_cancelbycustomer: "انصراف توسط مشتری",
  tbs_cashflowstate_actionmode: "در حال اقدام",
  tbrfinancialdataprovider: "حساب نزد کارگزار",
  taghadomcreated: "ایجاد حق تقدم",
  taghadomconvertedtomainsymbol: "تبدیل تقدم به سهم",
  taghadom: "حق تقدم",
  taban: "کارگزاری اعتبار تابان",
  tabaeerequesttype_s: "اعمال مطابق مقادیر درخواست شده",
  tabaeerequesttype_p: "اعمال حداکثری فیزیکی",
  tabaeerequesttype_m: "اعمال حداکثری اول نقدی و سپس فیزیکی",
  tabaeerequesttype_empty: "همه",
  tabaeerequestlistv2: "لیست تقاضاهای اعمال اوراق تبعی",
  tabaeerequestlist: "لیست تسویه اوراق تبعی",
  symbolstate_8: "ممنوع،محفوظ",
  symbolstate_7: "ممنوع،متوقف",
  symbolstate_6: "ممنوع،مسدود",
  symbolstate_5: "ممنوع",
  symbolstate_4: "مجاز،محفوظ",
  symbolstate_3: "مجاز،متوقف",
  symbolstate_2: "مجاز،مسدود",
  symbolstate_1: "مجاز",
  symbolstate_0: "عرضه نشده",
  symbolstate_: "-",
  symbolstate: "وضعیت نماد",
  symbol_nsccode: "نماد",
  symbol_marketunitname: "بازار",
  supervisor: "ناظر",
  sumblocked: "جمع بلوکه",
  successfullylogin: "ورود با موفقیت انجام شد",
  successfullupdate: "ثبت با موفقیت انجام شد.",
  strategymanagementagreement:
    "به دلیل عدم پذیرش توافق نامه استفاده از استراتژی های معاملاتی بازار اختیار ویا عدم تایید آن توسط کارگزار ،ثبت درخواست مقدور نمی باشد.",
  startdate_not_valid: "تاریخ ابتدا اشتباه است",
  simply_adminplus: "Simply",
  session_is_expired: "Session نامعتبر ",
  sepahfinancialdataprovider: "حساب بانک سپه",
  sentrequesttoengine: "ارسال درخواست به هسته معاملات",
  sent_to_bank_page: "ارسال شده به بانک",
  sendtobankpage: "ارسال شده به بانک",
  sendmultipleorderdenied:
    "ارسال سفارش دسته ای در این زمان امکان پذیر نمی باشد.",
  sendactivationcodedelayerror:
    "زمان در خواست کد فعال سازی از آخرین درخواست شما کمتر 2 دقیقه است. لطفا 2 دقیقه بعد درخواست خود را تکرار کنید.",
  send_verify_request: "درخواست verify",
  send_settle_request: "ارسال درخواست Settle",
  sell_adminplus: "فروش",
  sell: "فروش",
  selectpaymentdate: "روز پرداخت را وارد نمایید",
  selectbankaccount: "شماره حساب مقصد را وارد نمایید",
  selectamount: "مبلغ را وارد نمایید",
  second_board: "(2)خرده فروشی",
  se: "سهام عدالت",
  sarmayehfinancialdataprovider: "حساب بانک سرمایه",
  samankishfinancialgatewayprovideraccountname: "سامان کیش",
  samanfinancialdataprovider: "حساب بانک سامان قديم",
  samanboursarfinancialdataprovider: "حساب بانک سامان جدید",
  salemultipleordernotenable:
    "مشتری گرامی، با توجه به ابلاغیه سازمان تا اطلاع ثانوی امکان تقسیم سفارش فروش وجود ندارد.",
  saderat: "کارگزاري بانک صادرات‌",
  sadadfinancialdataprovider: "حساب بانک ملی",
  sadadaccount: "پرداخت الکترونیک سداد",
  rial: "ریال",
  reversed: "بازگشت خورده",
  request_amount_more_than_remain_and_block_value:
    "مبلغ درخواستی بیشتر مبلغ قابل برداشت است",
  remainfromtbs_adminplus: "مانده تی بی اس",
  refahfinancialgateway: "درگاه بانک رفاه",
  refahfinancialdataprovider: "بانک رفاه",
  received_from_bank: "دریافت اطلاعات از بانک",
  realbalancetitlemofid:
    "جمع مانده شامل مجموع مانده مشتری ، دارایی در صندوق حامی و مبلغ اعتبار می باشد",
  razavi: "کارگزاري رضوي",
  rahin: "کارگزاری راهین",
  quantitymorethanthebalanceofthecustomerbasket:
    "مقدار ارسال شده بيشتر از موجودي سبد مشتري است.",
  portfolio_marginsortage: "کمبود مارجين",
  portfolio_balance: "ارزش سبد",
  pleasetickcautionagreement:
    "لطفا ابتدا تیک تایید اطلاع از ابهام معاملات تحت احتیاط را بزنید",
  pleaseselectthemoneymorethan1000: "لطفا مبلغ را بیش از 1000 وارد نمایید",
  perordersell: "برای هر فروش",
  perorderbuy: "برای هر خرید",
  perorder: "برای هر سفارش",
  perdaysell: "یکبار در روز برای فروش",
  perdaybuy: "یکبار در روز برای خرید",
  perday: "یکبار در روز برای سفارش",
  paymentrequestissuccessfullycancelled:
    "درخواست وجه مورد نظر با موفقیت لغو شد",
  paymentimpossible: "برداشت وجه امکان پذیر نمی باشد",
  payment_adminplus: "دریافت از مشتری",
  pasargadfinancialdataprovider: "حساب بانک پاسارگاد",
  partiallymatched: "انجام بخشی از تراکنش",
  partiallyexecutionandexpired: "قسمتی از سفارش انجام و مابقی منقضی شد",
  partiallyexecution: "قسمتی از سفارش انجام شد",
  parsianfinancialdataprovider: "حساب بانک پارسیان",
  parsianaccount_parsian: "درگاه پرداخت پارسیان",
  parsianaccount: "تجارت الکترونيک پارسيان",
  ordervalidity_83: "جلسه معاملاتی",
  ordervalidity_74: "روز",
  ordervalidity_70: "معتبر تا لغو",
  ordervalidity_69: "انجام و حذف",
  ordervalidity_68: "معتبر تا تاریخ",
  ordersubmissionerror: "ثبت سفارش با خطا مواجه شد",
  orderstatev6_9011:
    "امکان کاهش موقعیت های اسپرد شده به دلیل کمبود مانده جهت تودیع وجه تضمین مقدور نمی باشد.",
  orderstatev6_9007: "امکان اخذ موقعیت فزاینده خرید وجود ندارد",
  orderstatev6_9006: "تعداد سفارش بیش از سقف مجاز تعیین شده برای مشتری می باشد",
  orderstatev6_9005: "امکان اخذ موقعیت فزاینده فروش وجود ندارد",
  orderstatev6_8049: "توافقنامه آتي انرژي امضا نشده است",
  orderstatev6_8048: "بازار آتي انرژي فعال نيست",
  orderstatev6_8047:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقعيت هاي باز کارگزار مي باشد",
  orderstatev6_8046:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقعيت هاي باز بازار مي باشد",
  orderstatev6_8045:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقعيت هاي باز مشتري مي باشد",
  orderstatev6_8043: "توافقنامه آتي امضا نشده است",
  orderstatev6_8041: "مقدار معامله خارج از محدوده تعریف شده در سیستم می باشد.",
  orderstatev6_8040: "عدم پذيرش سفارشاتي که احتمال معامله با خود را دارد",
  orderstatev6_8039:
    "عدم پذیرش سفارشات فروشی که منجر به ايجاد نوسان قيمتي بيشتر از 3 درصد",
  orderstatev6_8038:
    "عدم پذیرش سفارشات خریدی که منجر به ايجاد نوسان قيمتي بيشتر از 3 درصد",
  orderstatev6_8037:
    "سفارش فروش حداکثر به ميزان 50 %دامنه نوسان نسبت به قيمت آخرين معامله کمتر باشد",
  orderstatev6_8036:
    "سفارش خرید حداکثر به ميزان 50 %دامنه نوسان نسبت به قيمت آخرين معامله بيشتر باشد",
  orderstatev6_8035:
    "شما با توجه به دستورالعمل معاملات امکان ارسال سفارش بر روی این سهم را ندارید",
  orderstatev6_8034:
    "شما توافقنامه معاملات حرفه ای را قبول نکرده اید، در صورت تمایل از منوی توافقنامه ها وضیعت این توافقنامه را درحالت قبول قرار دهید",
  orderstatev6_8033:
    "باتوجه به وثیقه بودن نماد امکان ارسال سفارش فروش وجود ندارد",
  orderstatev6_8032:
    "عدم امکان ارسال سفارش فزاینده به خاطر رسیدن به سقف مجاز موقعیت های باز بازار",
  orderstatev6_8029: "در این بازه زمانی امکان حذف/ویرایش سفارش وجود ندارد",
  orderstatev6_8028: "در این بازه زمانی امکان حذف و ویرایش سفارش وجود ندارد",
  orderstatev6_8027:
    "امکان ثبت سفارش بر روی نمادهای اختیار فروش تبعی، بدون داشتن سهام پایه آن نماد، وجود ندارد.",
  orderstatev6_8026:
    "حداقل ارزش سفارش فروش در بازار سهام پنج میلیون ریال و در بازار پایه پنجاه میلیون ریال می باشد",
  orderstatev6_8024: "امکان ارسال سفارش فروش مدت دار وجود ندارد",
  orderstatev6_8018:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  orderstatev6_7000:
    "امکان وایریش سفارش وجود ندارد.جواب در خواست قبلی هنوز در سیستم ثبت نشده است",
  orderstatev6_6231: "شما مجاز به معامله در اين بازار نيستيد",
  orderstatev6_3581:
    "شما بيانيه انجام معامله در بازار پايه را قبول نکرده ايد یا در انتظار تایید کارگزاری است",
  orderstatev6_3500:
    "در حال حاضر امکان ارسال سفارش خرید بر روی این نماد امکان پذیر نمی باشد.",
  orderstatev6_3013: "خطاي محدوديت هاي عمومي",
  orderstatev6_2302: "امکان ارسال بيش از يک سفارش در عرضه اوليه وجود ندارد",
  orderstatev6_2137: "قيمت وارد شده خارج از محدوده است",
  orderstatev6_2115:
    "خطا! حجم وارد شده،خارج از محدوده تعریف شده در سیستم معاملات می باشد",
  orderstatev6_2045: "وضعيت سفارش اجازه عمليات ويرايش يا حذف را نمي دهد",
  orderstatev6_2022:
    "محدوده زمانی سفارش معتبر نمی باشد. محدوده زمانی مجاز برای ارسال درخواست 8:45 تا 12:30 میباشد.",
  orderstatev6_2014: "مبلغ سفارش می بایست مضربی از 10 باشد.",
  orderstatev6_2006:
    "حداقل ارزش سفارش خرید در بازار سهام پنج میلیون ریال و در بازار پایه پنجاه میلیون ریال می باشد",
  orderstatev6_2005:
    "تعداد سهام درخواستی باید مضربی از واحد  تعریف شده برای این نماد، باشد(مثلا ضریب 10 یا 100 و ...).",
  orderstatev6_1525: "خطا!موجودی سهام کافی نمی باشد.",
  orderstatev6_1110: "قیمت نماد خارج از رنج تعیین شده است",
  orderstatev6_1100: "مانده کافی نمیباشد",
  orderstatev6_1050: "فرآيند ثبت نام هنوز کامل نشده است",
  orderstatev6_1004: "وضعیت نماد  اجازه این فعالیت را نمی دهد.",
  orderstatev6_1003:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  orderstatev6_1001: "خطای محدودیت عمومی",
  orderstatev6_10009:
    "اخذ موقعیت فروش فزاینده صرفا از طریق استفاده از استراتژی های معاملاتی اختیار موجود در سامانه، امکان پذیر می باشد.",
  orderstatev6_10007:
    "به دلیل عدم پذیرش توافق نامه استفاده از راهبردهای (استراتژی های ) بازار اختیار معامله توسط کاربر و یا عدم تایید آن توسط کارگزار، امکان ثبت استراتژی مقدور نیست.",
  orderstatev6_10005:
    "اخذ موقعیت فروش فزاینده صرفا از طریق استفاده از استراتژی های معاملاتی اختیار موجود در سامانه امکان پذیر می باشد.",
  orderstatev6_10004:
    "به دلیل عدم وجود مانده مورد نیاز برای تودیع وجه تضمین ویرایش امکان پذیر نیست.",
  orderstatev6_10000:
    "امکان ارسال سفارش کاهنده به دلیل فعال بودن استراتژی بر روی نماد فوق مقدور نمی باشد.",
  orderstatev6_10: "زمان شرکت در عرضه اوليه به پايان رسيده است",
  orderstatev6_1: "مانده کافی نمیباشد",
  orderstatev4_9007: "امکان اخذ موقعیت فزاینده خرید وجود ندارد",
  orderstatev4_9006: "تعداد سفارش بیش از سقف مجاز تعیین شده برای مشتری می باشد",
  orderstatev4_9005: "امکان اخذ موقعیت فزاینده فروش وجود ندارد",
  orderstatev4_8049: "توافقنامه آتي انرژي امضا نشده است",
  orderstatev4_8048: "بازار آتي انرژي فعال نيست",
  orderstatev4_8041: "مقدار معامله خارج از محدوده تعریف شده در سیستم می باشد.",
  orderstatev4_8040: "عدم پذيرش سفارشاتي که احتمال معامله با خود را دارد",
  orderstatev4_8039:
    "عدم پذیرش سفارشات فروشی که منجر به ايجاد نوسان قيمتي بيشتر از 3 درصد",
  orderstatev4_8038:
    "عدم پذیرش سفارشات خریدی که منجر به ايجاد نوسان قيمتي بيشتر از 3 درصد",
  orderstatev4_8037:
    "سفارش فروش حداکثر به ميزان 50 %دامنه نوسان نسبت به قيمت آخرين معامله کمتر باشد",
  orderstatev4_8036:
    "سفارش خرید حداکثر به ميزان 50 %دامنه نوسان نسبت به قيمت آخرين معامله بيشتر باشد",
  orderstatev4_8035:
    "شما با توجه به دستورالعمل معاملات امکان ارسال سفارش بر روی این سهم را ندارید",
  orderstatev4_8034:
    "شما توافقنامه معاملات حرفه ای را قبول نکرده اید، در صورت تمایل از منوی توافقنامه ها وضیعت این توافقنامه را درحالت قبول قرار دهید",
  orderstatev4_8033:
    "باتوجه به وثیقه بودن نماد امکان ارسال سفارش فروش وجود ندارد",
  orderstatev4_8029: "در این بازه زمانی امکان حذف/ویرایش سفارش وجود ندارد",
  orderstatev4_8028: "در این بازه زمانی امکان حذف و ویرایش سفارش وجود ندارد",
  orderstatev4_8027:
    "امکان ثبت سفارش بر روی نمادهای اختیار فروش تبعی، بدون داشتن سهام پایه آن نماد، وجود ندارد.",
  orderstatev4_8026:
    "حداقل ارزش سفارش فروش در بازار سهام پنج میلیون ریال و در بازار پایه پنجاه میلیون ریال می باشد",
  orderstatev4_8024: "امکان ارسال سفارش فروش مدت دار وجود ندارد",
  orderstatev4_8018:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  orderstatev4_7000:
    "امکان وایریش سفارش وجود ندارد.جواب در خواست قبلی هنوز در سیستم ثبت نشده است",
  orderstatev4_6231: "شما مجاز به معامله در اين بازار نيستيد",
  orderstatev4_3581:
    "شما بيانيه انجام معامله در بازار پايه را قبول نکرده ايد یا در انتظار تایید کارگزاری است",
  orderstatev4_3500:
    "در حال حاضر امکان ارسال سفارش خرید بر روی این نماد امکان پذیر نمی باشد.",
  orderstatev4_2302: "امکان ارسال بيش از يک سفارش در عرضه اوليه وجود ندارد",
  orderstatev4_2137: "قيمت وارد شده خارج از محدوده است",
  orderstatev4_2115:
    "خطا! حجم وارد شده،خارج از محدوده تعریف شده در سیستم معاملات می باشد",
  orderstatev4_2045: "وضعيت سفارش اجازه عمليات ويرايش يا حذف را نمي دهد",
  orderstatev4_2022:
    "محدوده زمانی سفارش معتبر نمی باشد. محدوده زمانی مجاز برای ارسال درخواست 8:45 تا 12:30 میباشد.",
  orderstatev4_2014: "مبلغ سفارش می بایست مضربی از 10 باشد.",
  orderstatev4_2006:
    "حداقل ارزش سفارش خرید در بازار سهام پنج میلیون ریال و در بازار پایه پنجاه میلیون ریال می باشد",
  orderstatev4_2005:
    "تعداد سهام درخواستی باید مضربی از واحد  تعریف شده برای این نماد، باشد(مثلا ضریب 10 یا 100 و ...).",
  orderstatev4_1525: "خطا!موجودی سهام کافی نمی باشد.",
  orderstatev4_1110: "قیمت نماد خارج از رنج تعیین شده است",
  orderstatev4_1100: "مانده کافی نمیباشد",
  orderstatev4_1050: "فرآيند ثبت نام هنوز کامل نشده است",
  orderstatev4_1004: "وضعیت نماد  اجازه این فعالیت را نمی دهد.",
  orderstatev4_1003:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  orderstatev4_10013:
    "با توجه به محدودیت سقف مجاز موقعیت های هم جهت ، امکان ارسال سفارش فزاینده مقدور نمی باشد.",
  orderstatev4_10012:
    "با توجه به محدودیت سقف مجاز موقعیت های هم جهت ، امکان ارسال سفارش فزاینده مقدور نمی باشد.",
  orderstatev4_1001: "خطای محدودیت عمومی",
  orderstatev4_10: "زمان شرکت در عرضه اوليه به پايان رسيده است",
  orderstatev4_1: "مانده کافی نمیباشد",
  orderstatetype_sendstart: "شروع به ارسال",
  orderstatetype_sendfinish: "ارسال شده",
  orderstatetype_sendfailed: "خطا در ارسال سفارش",
  orderstatetype_delete: "حذف شده",
  orderstatetype_addtodatabase: "ذخیره اولیه",
  orderstatedate: "زمان ایجاد، ویرایش و حذف سفارش",
  orderstate_partiallyexecutionandexpired: "قسمتی از سفارش انجام و منقضی شد",
  orderstate_partiallyexecution: "قسمتی از سفارش انجام شد",
  orderstate_partiallyexcutionandexpired: "قسمتی از سفارش انجام و منقضی شد",
  orderstate_partiallyexcution: "بخشی از سفارش انجام شد",
  orderstate_orderexecuted: "سفارش اجرا شد",
  orderstate_onmodifyboard: "ثبت در سیستم معاملات(ویرایش شده)",
  orderstate_onmodify: "درحال ویرایش",
  orderstate_oncancelerror: "خطا! حذف سفارش انجام نشد",
  orderstate_onboard: "ثبت در سیستم معاملات",
  orderstate_modify: "ویرایش",
  orderstate_inomsqueue: "ارسال به کارگزاری",
  orderstate_freeze: "سفارش شما ثبت شد.در انتظار پایان دوره پذیره نویسی ",
  orderstate_expired: "سفارش منقضی شد",
  orderstate_error: "خطا",
  orderstate_done: "سفارش بصورت کامل انجام شد",
  orderstate_delete: "حذف ",
  orderstate_cancel: "سفارش از سیستم حذف شد",
  orderstate_30: "سفارش شما ثبت شد.در انتظار پایان دوره پذیره نویسی ",
  orderside_86: "فروش",
  orderside_65: "خرید",
  orderprice: "قیمت",
  orderfrom_web: "وب سایت",
  orderfrom_testsystem: "تست سیستم",
  orderfrom_tadbirmonitoring: "تست تدبیر",
  orderfrom_robot: "سفارش سرویس",
  orderfrom_onlineplus: "آنلاین پلاس",
  orderfrom_mobile: "موبایل",
  orderfrom_metatrader: "متاتریدر",
  orderfrom_metaapi: "متا تریدر",
  orderfrom_marketmaker: "بازار گردان",
  orderfrom_kaman: "کمان",
  orderfrom_conditionalorder: "سفارش شرطی",
  orderfrom_clientapi: "Client API",
  orderfrom_callcenter: "مرکز تماس",
  orderfrom_brokerapi: "BrokerApi",
  orderfrom_batchonlinetradeapi: "سفارش گروهی",
  orderfrom_basketorder: "سفارش دسته ای",
  orderfrom_api: "Api",
  optionspreadstrategyreusedlimitation:
    "این نماد دارای استراتژی اسپرد می باشد و امکان استفاده مجدد جهت اسپرد وجود ندارد",
  optionspreadstrategyopenorderexception:
    "امکان ثبت و تغییر استراتژی به علت داشتن سفارش باز مقدور نمی باشد",
  optionspreadbullcallspreadstrategystrikepriceshortage:
    "امکان ثبت و تغییر درخواست استراتژی به علت پایین بودن قیمت اعمال موقعیت فروش اختیار خرید از قیمت اعمال موقعیت خرید اختیار خرید مقدور نمی باشد .",
  optionspreadbearputspreadstrategystrikepricehigher:
    "امکان ثبت و تغییر درخواست استراتژی به علت پایین بودن قیمت اعمال موقعیت فروش اختیار فروش از قیمت اعمال موقعیت خرید اختیار فروش مقدور نمی باشد .",
  optiondefaultincreasingnotallowedforput:
    "غيرفعال سازي ارسال سفارش فزاينده فروش در اختيار فروش",
  optiondefaultincreasingnotallowedforcall:
    "غيرفعال سازي ارسال سفارش فزاينده فروش در اختيار خريد",
  optiondefaultincreasingdenied: "غيرفعال سازي ارسال سفارش فزاينده فروش",
  optiondefaultincreasingallowed: "فعال سازي ارسال سفارش فزاينده فروش",
  optioncoveredcallstrategyreusedlimitation:
    "این نماد دارای استراتژی کاورکال می باشد و امکان استفاده مجدد جهت کاورکال وجود ندارد",
  omsrule_rejected: "خطا! / خطای محدودیت های عمومی",
  oms_9006: "تعداد سفارش بیش از سقف مجاز تعیین شده برای مشتری می باشد",
  oms_9005: "امکان اخذ موقعیت فزاینده فروش وجود ندارد",
  oms_8047:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقعيت هاي باز کارگزار مي باشد",
  oms_8046:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقيعت هاي باز بازار مي باشد",
  oms_8045:
    "تعداد سفارش بيش از حد مجاز تعيين شده براي موقعيت هاي باز مشتري مي باشد",
  oms_8041: "مقدار معامله خارج از محدوده تعریف شده در سیستم می باشد.",
  oms_8035:
    "شما با توجه به دستورالعمل معاملات امکان ارسال سفارش بر روی این سهم را ندارید",
  oms_8034:
    "شما توافقنامه معاملات حرفه ای را قبول نکرده اید، در صورت تمایل از منوی توافقنامه ها وضیعت این توافقنامه را درحالت قبول قرار دهید",
  oms_8033: "باتوجه به وثیقه بودن نماد امکان ارسال سفارش فروش وجود ندارد",
  oms_8031: "عدم رعایت محدودیت حجم در هر سفارش",
  oms_8030:
    "شما توافق نامه انجام معامله در بازار مشتقه (آپشن) را قبول نکرده ايد یا توافق نامه تایید شده شما در انتظار تایید کارگزاری است",
  oms_8029: "در این بازه زمانی امکان حذف/ویرایش سفارش وجود ندارد",
  oms_8028: "در این بازه زمانی امکان حذف و ویرایش سفارش وجود ندارد",
  oms_8027:
    "امکان ثبت سفارش بر روی نمادهای اختیار فروش تبعی، بدون داشتن سهام پایه آن نماد، وجود ندارد.",
  oms_8026:
    "حداقل ارزش سفارش فروش در بازار سهام پنج میلیون ریال و در بازار پایه پنجاه میلیون ریال می باشد",
  oms_8022:
    "امکان ارسال سفارش از نوع معتبر تا لغو معتبر تا تاریخ برای سهم عرضه اولیه وجود ندارد",
  oms_8018:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  oms_7000:
    "امکان وایریش سفارش وجود ندارد.جواب در خواست قبلی هنوز در سیستم ثبت نشده است",
  oms_7: "درخواست خرید برای این سهامدار قبلا ثبت گردیده است",
  oms_3581:
    "شما بيانيه انجام معامله در بازار پايه را قبول نکرده ايد یا در انتظار تایید کارگزاری است",
  oms_3501: "نماد برای فروش مجاز نمی باشد",
  oms_3500: "امکان ارسال سفارش خريد در اين نماد وجود ندارد",
  oms_2090: "بازار بسته است",
  oms_2080: "محدودیت ارسال سفارش در ثانیه",
  oms_2026: "وضعیت سفارش اجازه عملیات ویرایش یا حذف را نمی دهد",
  oms_2016: "حجم وارد شده خارج از آستانه حجم تعيين شده است",
  oms_2007:
    ".حجم ریالی سفارش خارج از محدوده مقدار تعریف شده در سیستم می باشد■.حجم ریالی سفارش خارج از محدوده مقدار تعریف شده در سیستم می باشد.",
  oms_10009:
    "اخذ موقعیت فروش فزاینده صرفا از طریق استفاده از استراتژی های معاملاتی اختیار موجود در سامانه، امکان پذیر می باشد.",
  oms_10006:
    " به دلیل وجود درخواست تسویه برای نماد فوق امکان ثبت درخواست وجود ندارد",
  oms_10005:
    "امکان ثبت درخواست تسویه نقدی برای موقعیت های باز خرید وثیقه شده جهت استفاده در استراتژی های اختیار مقدور نمی باشد.",
  oms_10000:
    "امکان ارسال سفارش کاهنده به دلیل فعال بودن استراتژی بر روی نماد فوق مقدور نمی باشد.",
  ok: "تراکنش با موفقیت انجام شد",
  nsc_020015: "ارتباط با هسته معاملات با مشکل مواجه شده است",
  nsc_009999: "ارتباط با هسته معاملات با مشکل مواجه شده است",
  nsc_003501: "قیمت داده شده خارج از محدوده می باشد.",
  nsc_003500: "معامله گر نامعتبر",
  nsc_003069: "مقدار واحد پول نامعتبر برای نماد، نماد در حالت ممنوع است.",
  nsc_002137: "قيمت وارد شده خارج از آستانه قيمت تعيين شده است",
  nsc_002003: "قيمت سهم وارد نشده است",
  nsc_001525: "موجودی سهام ، کافی نمی باشد.",
  nsc_001523:
    "خطا! محدوده معتبر برای سرمایه فراتر از حد تعیین شده طبق مقررات می باشد.",
  nsc_001003:
    "وضعیت گروه اجازه این فعالیت را نمی دهد.زمان فعالیت بازارها : \n\u003c/br\u003e\nسهام و حق تقدم، صندوق های سهامی و مختلط 8:45 تا 12:30\n\u003c/br\u003e\nصندوق های درآمد ثابت و اوراق  8:25 تا 15\n\u003c/br\u003e\nصندوق ها و سپرده های کالایی طلا 11:30 تا 15",
  notregisteredphysicalrequest: "عدم ثبت درخواست-فیزیکی",
  notregisteredcashrequest: "عدم ثبت درخواست-نقدی",
  notenoughpositioncount: "تعداد موقعیت درخواستی بیشتر از موقعیت های باز است",
  notenoughmoney: "عدم موجودی کافی",
  none_adminplus: "هیچکدام",
  newrealtimeportfolioadvanced: "پرتفوی لحظه ای پیشرفته",
  newentry: "درخواست جدید",
  morethanoneuserfound:
    "شماره همراه براي چند مشتري ثبت شده است، لطفا کدملي يا نام کاربري را وارد نماييد.",
  moneyreceiptstate_tbs_cashflowstate_unknown: "نامعلوم",
  moneyreceiptstate_tbs_cashflowstate_troubleshooting: "در حال رفع مشکل",
  moneyreceiptstate_tbs_cashflowstate_reviewmode: "در حال بررسی",
  moneyreceiptstate_tbs_cashflowstate_done: "اقدام گردید",
  moneyreceiptstate_tbs_cashflowstate_deleted: "حذف گردید",
  moneyreceiptstate_tbs_cashflowstate_cancelbycustomer: "انصراف توسط مشتری",
  moneyreceiptstate_tbs_cashflowstate_actionmode: "در حال اقدام",
  moneyreceiptstate_confirmed: "تایید شده",
  moneyreceiptstate_beingprocessed: "درحال ارسال",
  moneypayment_troubleshooting: "رفع اشکال",
  moneypayment_report: "گزارش دریافت وجه",
  moneypayment_notset: "نامشخص",
  moneypayment_none: "هیچکدام",
  moneypayment_all: "همه",
  mobinsarmayeh: "کارگزاری مبین سرمایه",
  mobileview: "موبایل ویو",
  middleeastfinancialdataprovider_samankish: "درگاه سامان کیش",
  middleeastfinancialdataprovider: "درگاه خاور میانه",
  mellifinancialdataprovider: "حساب بانک ملی",
  melli: "کارگزاری بانک ملی",
  mellatfinancialgatewayprovideraccountname: "به پرداخت ملت",
  mellatbankfinancialdataprovider: "حساب بانک ملت",
  mellataccount_behpardakht: "به پرداخت ملت",
  mellataccount: "حساب ملت",
  maxorderquantityerror: "حداکثر تعداد سفارش {0} می باشد",
  maskanfinancialdataprovider: "حساب نزد بانک مسکن",
  maskan: "کارگزاری بانک مسکن",
  "markettype.zaminetf": "ETF زمین و ساختمان",
  "markettype.tsefuture": "بازار آتی",
  "markettype.stocketf": "ETF سهام",
  "markettype.selloption": "اختیار فروش",
  "markettype.option": "اوراق اختیار تبعی",
  "markettype.mixedetf": "ETF مختلط",
  "markettype.kalaenergy": "کالا انرژی",
  "markettype.fixedetf": "ETF اوراق با درامد ثابت",
  "markettype.faraboursestock": "فرابورس سهام",
  "markettype.faraboursemaskan": "مسکن فرابورس",
  "markettype.faraboursebond": "اوراق مشارکت فرابورسی",
  "markettype.faraboursebase": "پایه فرابورس",
  "markettype.exchangestock": "سهام بورس",
  "markettype.exchangebond": "اوراق مشارکت بورسی",
  "markettype.energygovahi": "گواهی انرژی",
  "markettype.energyfuture": "آتی انرژی",
  "markettype.commodity": "بورس کالا",
  "markettype.buyoption": "اختیار خرید",
  "markettype.buybackoption": "اختیار فروش تبعی",
  "markettype.atistock": "آتی سهام",
  margincustomerstatus_normal: "عادی",
  margincustomerstatus_margincall: "اخطار افزایش وجه تضمین",
  margincustomerstatus_atrisk: "درخطر",
  margincustomerstatus_3: "اخطار افزایش وجه تضمین",
  margincustomerstatus_2: "درخطر",
  margincustomerstatus_1: "عادی",
  margincustomerstatus: "وضعیت اختیار",
  madde15_volumepattern: "سفارشات دارای الگوی حجمی در جدول مظنه ها",
  madde15_topquote: "دستکاری پنج مظنه برتر",
  madde15_shockprice_positive: "انجام معامله با اعمال رنج مثبت",
  madde15_shockprice_negative: "انجام معامله با اعمال رنج منفی",
  madde15_samevolumepattern: "سفارشات با حجم یکسان در جدول مظنه ها",
  madde15_deleteorder: "حذف کردن سفارشات مدت دار در پیش گشایش",
  madde15_consecutiveorders: "ارسال سفارشات متوالي",
  madde15_basevolume: "معامله جهت پرکردن حجم مبنا",
  login_user_msg: "یک ورود همزمان به این حساب کاربری انجام شد.",
  linkmanager: "مدیریت لینک",
  lastorderstatetime: "زمان درخواست",
  khavarmiyanehfinancialdataprovider: "حساب نزد بانک خاور میانه",
  kharazmi_theme: "اطلس",
  karafarinfinancialdataprovider: "حساب بانک کارآفرین",
  karafarin: "کارگزاري بانک کارآفرين",
  isnotprofitable: "موقعیت در زیان میباشد",
  isatis: "کارگزاری ایساتیس پویا",
  iranzaminaccount: "حساب ایران زمین",
  irankishnewfinancialgatewayprovider: "ایران کیش (جدید)",
  invalidverifycode: "کد وارد شده معتبر نمی باشد",
  insert_to_tbs: "در حال ارسال به TBS",
  insert_to_rayan_hamafza_service: "ارسال به بک آفیس رایان هم افزا",
  insert_to_automation: "ارسال به اتوماسیون",
  inprogress: "انتظار",
  index_adminplus: "شاخص",
  groupstateid9: "پایان مشاوره",
  groupstateid8: "پایان مشاوره",
  groupstateid7: "مداخله ناظر",
  groupstateid6: "پایان معاملات پیوسته",
  groupstateid5: "معاملات پیوسته",
  groupstateid4: "بستن/گشایش",
  groupstateid3: "گشایش",
  groupstateid2: "پیش گشایش",
  groupstateid11: "متوقف",
  groupstateid10: "ممنوع",
  groupstateid1: "شروع مشاوره",
  groupstateid0: "نا مشخص",
  good_till_date: "معتبر تا تاریخ",
  good_till_cancelled: "معتبر تا لغو",
  good_till_cancel: "معتبر تا لغو",
  giftstock: "سهام جایزه",
  future_adminplus: "آتی",
  fourth_board: "(4)عمده",
  fouladmabna: "کارگزاری دلیران پارس",
  first_request_sent: "درخواست اولیه ارسال شد",
  first_board: "(1)نماد اصلی",
  fill_kill: "انجام و حذف",
  fill_and_kill: "انجام و حذف",
  filesizeismorethan500k: "حجم فایل نباید بیشتر از 500 کیلو بایت باشد.",
  filesizeismorethan4m: "حجم فایل نباید بیشتر از 4 مگابایت باشد.",
  fileformatisnotvalid: "فرمت فایل ارسالی نامعتبر است",
  farabourseindex: "شاخص فرابورس",
  failed: "خطا",
  errorinoperation: "خطا در انجام عملیات",
  error_in_verify_request: "خطا در عملیات verify",
  error_in_settle_request: "خطا درارسال درخواست Settle",
  error_in_redirect_from_bank_page: "خطا در ارسال به بانک",
  error_in_insert_to_tbs: "خطا در ارسال به TBS",
  error_in_insert_to_rayan_hamafza_service:
    "خطا در ارسال به بک آفیس رایان هم افزا",
  error_in_insert_to_automation: "خطا در ارسال به اتوماسیون",
  error_in_first_request: "خطا در ارسال درخواست اولیه",
  error_in_bank_operation: "خطا در عملیات بانکی",
  error_in_add_voucher_accounting: "خطا در اعتبار دهی",
  enteghal_adminplus: "انتقال",
  enovinfinancialdataprovider: "حساب بانک اقتصادنوین",
  enovin: "کارگزاری اقتصادنوین",
  engineansweredrequest: "دریافت پاسخ از هسته معاملات",
  engineansweredphysicalrequest: "دریافت پاسخ از هسته معاملات-فیزیکی",
  engineansweredcashrequest: "دریافت پاسخ از هسته معاملات-نقدی",
  ending_adminplus: "اتمام",
  enddate_not_valid: "تاریخ انتها اشتباه است",
  editoptionstrategy:
    "به دلیل عدم وجود درخواست استراتژی امکان ویرایش و حذف مقدور نمی باشد.",
  ebtal_adminplus: "ابطال",
  draft: "پیش نویس",
  donyaenovin: "کارگزاری دنیای نوین",
  description: "شرح",
  deleteoptionstrategyrequest:
    "حذف درخواست به دلیل وجود یک درخواست باز با وضعیت حذف، امکان پذیر نیست",
  deletedbyadmin: "حذف توسط ادمین",
  day: "روز",
  daryaft_adminplus: "پرداخت به مشتری",
  customertag_adminplus: "دسته مشتریان",
  customersclub: "باشگاه مشتریان",
  customerhamibalance_credit: "مانده حامی",
  customerbalance_remain: "مانده مشتری",
  customerbalance_realbalance: "جمع مانده",
  customerbalance_margincustomerstatus: "وضعیت حساب مشتقه",
  customerbalance_hami: "صندوق حامی",
  customerbalance_derivative: "قدرت خرید مشتقه",
  customerbalance_credit: "مبلغ اعتبار",
  customerbalance_blockedbalance: "بلوکه شده",
  customerbalance_accountbalance: "قدرت خرید",
  customeragreementstatetype_watingforadminconfirm: "در انتظار تایید کارگزاری",
  customeragreementstatetype_notseen: "مشاهده نشده",
  customeragreementstatetype_ignore: "رد شده",
  customeragreementstatetype_accessdenied: "عدم دسترسی",
  customeragreementstatetype_accept: "قبول کرده",
  customer_customerid: "مشتری و دسته مشتریان",
  customer_adminplus: "مشتری",
  creditfromtbs_adminplus: "اعتبار تی بی اس",
  "connection not available": "مشکل ارتباط رخ داده است.",
  completed: "انجام شده",
  clsdes_admin_reports_orderstatemodal: "clsdes_admin_reports_orderstatemodal",
  checkusernameformat: "فرمت نام کاربری صحیح نیست.",
  changeuserduplicate: "نام کاربری تکراری است",
  changebrokerstate_lackofassets: "عدم دارایی",
  changebrokerstate_inprogressfa: "در حال بررسی",
  changebrokerstate_inprogress: "درحال بررسی",
  changebrokerstate_freeze: "فریز",
  changebrokerstate_dissuasioned: "انصراف توسط کاربر",
  changebrokerstate_buycredit: "خرید اعتباری",
  changebroker_withtransfercertificate:
    "آخرین معامله در این کارگزاری صورت گرفته است",
  changebroker_withlasttradeinbrokrage:
    "اصل گواهی نامه نقل و انتقال سهام به کارگزاری تحویل شده است",
  changebroker_certificatenumber: "شماره گواهینامه",
  capitalincrease: "افزایش سرمایه",
  canceled_from_customer: "انصراف توسط مشتری",
  buymultipleordernotenable:
    "مشتری گرامی، با توجه به ابلاغیه سازمان تا اطلاع ثانوی امکان تقسیم سفارش خرید وجود ندارد.",
  buy_adminplus: "خرید",
  buy: "خرید",
  boursekalagovahisiman_adminplus: "گ.سپرده کالایی با مالیات ا.افزوده",
  blockamount: "ارزش سفارش",
  begining_adminplus: "آغاز",
  bankorderduplicate: "تراکنش تکراری بانک",
  bank_unknown: "هیچکدام",
  bank_tosehtaavon: "توسعه تعاون",
  bank_toseehsaderat: "توسعه صادرات",
  bank_tosee: "توسعه",
  bank_tejarat: "تجارت",
  bank_tat: "تات",
  bank_sina: "سینا",
  bank_shahr: "شهر",
  bank_sepah: "سپه",
  bank_sarmaye: "سرمایه",
  bank_sanatomadan: "صنعت و معدن",
  bank_saman: "سامان",
  bank_saderat: "صادرات",
  bank_resalat: "رسالت",
  bank_refah: "رفاه",
  bank_postbank: "پست بانک",
  bank_pasargad: "پاسارگاد",
  bank_parsian: "پارسیان",
  bank_others: "هیچکدام",
  bank_noor: "نور",
  bank_mellisiba: "ملی سیبا",
  bank_melli: "ملی",
  bank_mellat: "ملت",
  bank_mehriran: "مهرایران",
  bank_mehreghtesad: "مهراقتصاد",
  bank_maskan: "مسکن",
  bank_markazi: "مرکزی",
  bank_kowsar: "کوثر",
  bank_khavarmianeh: "خاورمیانه",
  bank_keshavarzi: "کشاورزی",
  bank_kaspian: "کاسپین",
  bank_karafarin: "کارآفرین",
  bank_iranzamin: "ایران زمین",
  bank_iranvenezuela: "ایران ونزولا",
  bank_hekmat: "حکمت",
  bank_ghavamin: "قوامین",
  bank_gardeshgari: "گردشگری",
  bank_etebaritose: "اعتباری توسعه",
  bank_eghtesadnovin: "اقتصادنوین",
  bank_day: "دی",
  bank_askarie: "عسکریه",
  bank_ansar: "انصار",
  autonewentry: "محاسبات سیستم",
  asanpardakhtgperror_507: "خطا در انجام عملیات لطفا مجدد سعی نمایید",
  asanpardakhtgperror_489: "خطا در انجام عملیات لطفا مجدد سعی نمایید",
  asanpardakhtgperror_486: "خطا در انجام عملیات لطفا مجدد سعی نمایید",
  asanpardakhtgperror_: "خطا در انجام عملیات لطفا مجدد سعی نمایید",
  asanpardakht: "آسان پرداخت",
  aryabourse: "کارگزاری دانایان",
  arg: "کارگزاری ارگ هومن",
  ansarfinancialdataprovider: "حساب بانک انصار",
  amountisnotvalid: "مبلغ صحیح نمی باشد",
  allusers_adminplus: "همه کاربران سيستم",
  allcustomer_adminplus: "همه مشتریان",
  all_adminplus: "همه",
  adminplus_web: "وب سایت",
  adminplus_testsystem: "تست سیستم",
  adminplus_tadbirmonitoring: "تست تدبیر",
  adminplus_robot: "سفارش سرویس",
  adminplus_onlineplus: "آنلاین پلاس",
  adminplus_mobileview: "همراه پلاس",
  adminplus_mobilegateway: "موبایل",
  adminplus_mobile: "موبایل",
  adminplus_metatrader: "متاتریدر قدیم",
  adminplus_metaapi: "متاتریدر جدید",
  adminplus_marketmaker: "بازار گردان",
  adminplus_conditionalorder: "سفارش شرطی",
  adminplus_clientapi: "Client API",
  adminplus_callcenter: "مرکز تماس",
  adminplus_brokerapi: "Broker Api",
  adminplus_batchonlinetradeapi: "سفارش گروهی",
  adminplus_basketorder: "سفارش دسته ای",
  adminplus_api: "Api",
  adminplus_adminplus: "ادمین پلاس",
  admin_reports_orderstatemodal: "وضعیت سفارش",
  admin_imefutureonline_orderstatemodal: "وضعیت سفارش",
  admin_exchangesymbol_tabaeerequestlistv2: "لیست تقاضاهای اعمال اوراق تبعی",
  admin_customer_offlineorderv2: "سفارشات عرضه اولیه مشتری",
  add_voucher_accounting: "اعتبار دهی",
  activeoptionstrategy:
    "ثبت درخواست جدید به دلیل وجود یک درخواست باز با وضعیت درحال بررسی، امکان پذیر نیست. لطفا در صورت نیاز به تغییر ، درخواست باز موجود را ویرایش نمایید.",
  activatesuccess: "فعال سازی با موفقیت انجام شد",
  account_market_and_cashflowtype_market_does_not_match:
    "شماره حساب ثبت شده شما در کارگزای با مشکل مواجه شده است",
  30: "سفارش شما ثبت شد.در انتظار پایان دوره پذیره نویسی ",
  _provider: "نوع حساب (محل خرید)",
};
window.RTLLTRDirection = "rtl";
window.RTLLTRInvDirection = "ltr";
