const USER_NAME = process.env.USER_NAME;
const PASSWORD = process.env.PASSWORD;
const GET_CAPTCHA_ENDPOINT = process.env.GET_CAPTCHA_ENDPOINT;
const LOGIN_ENDPOINT = process.env.LOGIN_ENDPOINT;
const PORTFOLIO_ENDPOINT = process.env.PORTFOLIO_ENDPOINT;
const ALL_SYMBOLS_ENDPOINT = process.env.ALL_SYMBOLS_ENDPOINT;
const ALL_SECTORS_ENDPOINT = process.env.ALL_SECTORS_ENDPOINT;
const NAV_DATA_ENDPOINT_TEMPLATE = process.env.NAV_DATA_ENDPOINT_TEMPLATE;
const POST_ORDER_ENDPOINT = process.env.POST_ORDER_ENDPOINT;

const LIGHTSTREAMER_ENDPOINT = process.env.LIGHTSTREAMER_ENDPOINT;
const BROKER_ID = process.env.BROKER_ID;


